removed unwanted data fields from API responses
dvstechlabs/Noteslify pull request #261
Opened 2023-01-08 13:15 UTC by thevinitgupta

## Describe your changes
Removed the unwanted data being send to the frontend from the API
Also, replaced with success message where needed.

## Screenshots - If Any (Optional)

## Issue ticket number and link - If Any
#217 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

## Additional Information (Optional)

2023-01-08 13:42 UTC, devarshishimpi approved these changes
LGTM! Make sure to commit the package-lock.json file as well. I know it's not recommended to add, but seems like we need for particular versioning

2023-01-08 13:43 UTC, devarshishimpi commented
@Gauravdarkslayer @abhinandanwadwa Kindly merge the PR after any of the second reviews completes!

2023-01-08 13:49 UTC, Gauravdarkslayer commented
@thevinitgupta @devarshishimpi I guess the same thing goes for the folder section as well.

2023-01-08 13:51 UTC, Gauravdarkslayer commented on apps/web/backend/routes/notes.js
> +            notesList.push({
Without pushing it to a new array, the unwanted key can also be deleted.

2023-01-08 13:52 UTC, Gauravdarkslayer reviewed
Without pushing it to a new array, the unwanted key can also be deleted, so that we don't need an extra array.

2023-01-08 13:55 UTC, Gauravdarkslayer commented on apps/web/backend/routes/notes.js
> +            notesList.push({
Need to implement the same for the folder section routes.

2023-01-08 13:56 UTC, thevinitgupta commented
It is a `const` array. That is why I added a new array to return the required data.

2023-01-08 14:15 UTC, abhinandanwadwa requested changes
https://github.com/dvstechlabs/Noteslify/blob/1bcd840142bb9fd27146771dec540719a5ead527/apps/web/backend/routes/folders.js#L37

https://github.com/dvstechlabs/Noteslify/blob/1bcd840142bb9fd27146771dec540719a5ead527/apps/web/backend/routes/folders.js#L186

https://github.com/dvstechlabs/Noteslify/blob/1bcd840142bb9fd27146771dec540719a5ead527/apps/web/backend/routes/folders.js#L211

Here are few more

2023-01-08 15:53 UTC, thevinitgupta commented
@abhinandanwadwa shall I work on the folders route or wait for @devarshishimpi ?

2023-01-08 15:58 UTC, abhinandanwadwa commented
@thevinitgupta Go ahead with folder routes

2023-01-08 16:34 UTC, thevinitgupta commented
@abhinandanwadwa updated the folders routes.

2023-01-08 16:53 UTC, abhinandanwadwa approved these changes

2023-01-08 17:07 UTC, Gauravdarkslayer reviewed
Please use the delete key method I've mentioned earlier rather than creating a new array of objects.

2023-01-08 18:51 UTC, devarshishimpi approved these changes

2023-01-08 18:52 UTC, devarshishimpi commented
> Please use the delete key method I've mentioned earlier rather than creating a new array of objects.

@Gauravdarkslayer Is the required changes necessary or could we merge the PR?

2023-01-08 19:04 UTC, Gauravdarkslayer commented
They are not necessary but its required for performance & space related optimizations.
@devarshishimpi

2023-01-08 19:32 UTC, devarshishimpi commented
> They are not necessary but its required for performance & space related optimizations. @devarshishimpi

Great, @thevinitgupta Could you complete the required change as well?

2023-01-09 05:51 UTC, thevinitgupta commented
@Gauravdarkslayer can I use the `select` method of the Schema prototype in this way : 
```javascript
const allNotes = await NoteSchema.find({ authorId: req.user.id, isDeleted: false }).select({_id : 1, title : 1, description : 1, createdAt : 1, secretKey : 1}).sort({ createdAt: -1 });
```

This way, we'll only need to delete the `secretKey`.

2023-01-09 06:37 UTC, Gauravdarkslayer commented
@thevinitgupta Yes you can do this, but please make sure to be consistent throughout the application. Like if you are doing this for notes routes and do the same for folder routes as well.

2023-01-10 04:32 UTC, thevinitgupta commented
Sure, I will do that.

2023-01-10 04:45 UTC, thevinitgupta commented
I have added the `select` query and used the `delete` key method for the notes and folders routes.

2023-01-10 04:58 UTC, Gauravdarkslayer approved these changes
LGTM !

2023-01-10 05:22 UTC, merged